### ISSUE TITLE
Assertions failing with Tartarus Swarm in 1.0.10

### ISSUE THREAD

**Issue by jeremG** [andor9/tyrant_optimize#1] opened 2013-04-07 20:56 UTC
An older version I'd compiled on 3/28 doesn't have this issue when I ran it with the same parameters.  Here's a log:

> C:\t_o>o ts http://tyrant.40in.net/kg/deck.php?nid=QNJeCtJ6JLJwu8 -rf
> 
> C:\t_o>tyrant_optimize.exe QNJeCtJ6JLJwu8 "Tartarus Swarm" -o -o=add.txt climb 25000 -r -fixedlen
> Attacker: Deck: QNJeCtJ6JLJwu8
> Defender: Raid #7 "Tartarus Swarm"
> win%: 99.372 (24843 out of 25000)
> 99.372%: Alaric, Ayrkrane, Rifter, Marshal, Disposer, Iron Maiden, Electromagnetic Pulse
> Assertion failed: summoned->m_type == CardType::assault || summoned->m_type == CardType::structure, file sim.cpp, line 2164
> 
> This application has requested the Runtime to terminate it in an unusual way.
> Please contact the application's support team for more information.

Those last four lines of a failed assert() are printed out 3 more times before a Windows(Win7 x64) error message pops up and aborts the process.

**Comment by 12345ieee** [comment] 2013-04-08 15:23
Same Problem here, but "sim" option is perfectly fine for me (v 1.0.10):

C:\tyrant_optimize>tyrant_optimize.exe RbI2IGJeAeJwGu "Tartarus Swarm" sim 10000
Attacker: Deck: RbAeGuIGI2JeJw
Defender: Raid #7 "Tartarus Swarm"
win%: 91.43 (9143 out of 10000)
draw%: 0.02 (2 out of 10000)
loss%: 8.55 (855 out of 10000)
ANP: 22.5467

C:\tyrant_optimize>tyrant_optimize.exe RbI2IGJeAeJwGu "Tartarus Swarm" climb 10000
...
...
This gives the same exact error as jeremG's.

However I found a workaround by changing "Split" into "Summon Itself" on cards.xml, so I think the error is in the Split code.

Hope it helps.

12345ieee

**Comment by andor9** [comment] 2013-04-12 07:02
Thank you. It has been fixed in 1.0.11.
It is caused by Mimicking Split skill.
Note that the workaround leads to wrong results if any card with Mimic skill is recommended, because Summon is mimicable while Split is not.

**Closed as completed by andor9** 2013-04-12 07:02 UTC
Labels: bug
